services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - "./:/app"
    env_file:
      - .env
